import { z } from "zod";

/**
 * Skill metadata extracted from frontmatter.
 */
export interface SkillMetadata {
  name: string;
  description: string;
  tools: string[];
}

/**
 * Parsed skill file.
 */
export interface Skill {
  metadata: SkillMetadata;
  content: string;
  filePath: string;
}

/**
 * Skill execution step types.
 */
export type SkillStepType = "sql" | "semantic" | "reason";

/**
 * Conditional branch for multi-step execution.
 */
export interface ConditionalBranch {
  condition: string;
  ifTrue: string;
  ifFalse: string;
}

/**
 * Single step in a skill execution plan.
 */
export interface SkillStep {
  id: string;
  type: SkillStepType;
  
  // For SQL steps
  sql?: string;
  
  // For semantic steps
  semanticQuery?: string;
  semanticFilters?: {
    app_names?: string[];
    time_range?: {
      start?: string;
      end?: string;
    };
  };
  
  // For reason steps
  reasoningPrompt?: string;
  inputVariables?: string[];
  
  // Execution control
  dependsOn: string[];
  conditionalNext?: ConditionalBranch;
}

/**
 * Complete skill execution plan.
 */
export interface SkillPlan {
  goal: string;
  selectedSkills: string[];
  requiresMultiStep: boolean;
  steps: SkillStep[];
}

/**
 * Result of a skill step execution.
 */
export interface SkillStepResult {
  stepId: string;
  type: SkillStepType;
  success: boolean;
  data?: unknown;
  error?: string;
  rowCount?: number;
  executionTimeMs?: number;
}

/**
 * Zod schema for SQL execution input.
 */
export const SqlExecuteInputSchema = z.object({
  sql: z.string().min(1).describe("SQLite SELECT query to execute"),
});

export type SqlExecuteInput = z.infer<typeof SqlExecuteInputSchema>;

/**
 * Zod schema for semantic search input.
 */
export const SemanticSearchInputSchema = z.object({
  query: z.string().min(1).describe("Natural language query for embedding search"),
  limit: z.number().int().min(1).max(100).default(20),
  offset: z.number().int().min(0).max(60).default(0).optional(),
  filters: z.object({
    app_names: z.array(z.string()).optional(),
    time_range: z.object({
      start: z.string().datetime({ offset: true }).optional(),
      end: z.string().datetime({ offset: true }).optional(),
    }).optional(),
  }).optional(),
});

export type SemanticSearchInput = z.infer<typeof SemanticSearchInputSchema>;

/**
 * Zod schema for web search input.
 */
export const WebSearchInputSchema = z.object({
  query: z.string().min(1).describe("Natural language query for public web search"),
  limit: z.number().int().min(1).max(10).default(5),
});

export type WebSearchInput = z.infer<typeof WebSearchInputSchema>;

/**
 * Zod schema for current datetime tool input.
 */
export const CurrentDateTimeInputSchema = z.object({});

export type CurrentDateTimeInput = z.infer<typeof CurrentDateTimeInputSchema>;

/**
 * Zod schema for skill plan generated by LLM.
 */
export const SkillPlanSchema = z.object({
  goal: z.string().describe("What the user is trying to achieve"),
  selectedSkills: z.array(z.string()).describe("Which skills are being used"),
  requiresMultiStep: z.boolean().describe("Whether LLM reasoning is needed between steps"),
  steps: z.array(z.object({
    id: z.string(),
    type: z.enum(["sql", "semantic", "reason"]),
    sql: z.string().optional(),
    semanticQuery: z.string().optional(),
    semanticFilters: z.object({
      app_names: z.array(z.string()).optional(),
      time_range: z.object({
        start: z.string().optional(),
        end: z.string().optional(),
      }).optional(),
    }).optional(),
    reasoningPrompt: z.string().optional(),
    inputVariables: z.array(z.string()).optional(),
    dependsOn: z.array(z.string()).default([]),
    conditionalNext: z.object({
      condition: z.string(),
      ifTrue: z.string(),
      ifFalse: z.string(),
    }).optional(),
  })),
});

/**
 * SQL validation result.
 */
export interface SqlValidationResult {
  valid: boolean;
  error?: string;
  normalized?: string;
}
